<?php
/**
 * Copyright 2016 Henrik Hedelund
 *
 * This file is part of Henhed_Piwik.
 *
 * Henhed_Piwik is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Henhed_Piwik is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Henhed_Piwik.  If not, see <http://www.gnu.org/licenses/>.
 */

?>
<?php /* @var $block \Henhed\Piwik\Block\Piwik */ ?>
<script type="text/x-magento-init">
    <?php echo $block->jsonEncode([
        '*' => [
            'Henhed_Piwik/js/tracker' => $block->getJsOptions()
        ]
    ]); ?>
</script>

<script type="text/javascript">
    require( ['Henhed_Piwik/js/tracker'], function () {
        (function(){
            _paq.push(['setTrackerUrl', '<?php echo $block->escapeJsQuote($block->getTrackerUrl()); ?>']);
            _paq.push(['setSiteId', '<?php echo $block->getSiteId(); ?>']);
            _paq.push(["setDocumentTitle", document.domain + "/" + document.title]);
            _paq.push(["setDoNotTrack", true]);
            _paq.push(['trackPageView']);

            // if (!window.Piwik.getAsyncTrackerPromise().length) {
            //     window.Piwik.addTracker();
            // }

            var d=document,
                g = d.createElement('script'),
                s = d.getElementsByTagName('script')[0];
            g.type = 'text/javascript';
            g.async = true;
            g.defer = true;
            g.src = '<?php echo $block->escapeJsQuote($block->getScriptUrl()); ?>';
            s.parentNode.insertBefore(g,s);
        });
    });
</script>
<noscript><span><img src="<?php echo $block->getTrackingPixelUrl(); ?>" style="border: 0; line-height: 0px" alt="" /></span></noscript>
