<?php
/**
 * Copyright 2016-2018 Henrik Hedelund
 *
 * This file is part of Henhed_Piwik.
 *
 * Henhed_Piwik is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Henhed_Piwik is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Henhed_Piwik.  If not, see <http://www.gnu.org/licenses/>.
 */

?>
<?php /** @var \Henhed\Piwik\Block\Piwik $block */ ?>
<script type="text/x-magento-init">
<?= $block->jsonEncode([
    '*' => [
        'Henhed_Piwik/js/tracker' => $block->getJsOptions()
    ]
]); ?>
</script>
<?php
// The following script can be omitted in which case the
// `Henhed_Piwik/js/tracker' component will inject the tracker script instead.
// However that might cause the tracker script to miss the `DOMContentLoaded'
// event which breaks the link tracking feature.
?>
<script type="text/javascript">
(function (w, d) {
    w._paq = w._paq || [];
    w._paq.push(['setTrackerUrl', '<?= $block->escapeJsQuote($block->getTrackerUrl()); ?>']);
    w._paq.push(['setSiteId', <?= (int) $block->getSiteId(); ?>]);
    var g = d.createElement('script'),
        s = d.getElementsByTagName('script')[0];
    g.type = 'text/javascript';
    g.async = true;
    g.defer = true;
    g.src = '<?= $block->escapeJsQuote($block->getScriptUrl()); ?>';
    s.parentNode.insertBefore(g, s);
})(window, document);
</script>
<?php
// The following script is a workaround that prevents the checkout loader
// overlay from spinning indefinitely in cases where a browser plugin such as
// AdBlock stops the tracker JS component from loading. The loader indicator
// relies on require's module registry to decide when to hide itself so here we
// export a mocked version of the component if we get an `errback' from require.
// @see vendor/magento/module-checkout/view/frontend/web/js/checkout-loader.js
// @see lib/web/mage/requirejs/resolver.js
?>
<script type="text/javascript">
(function (require, undefined) {
    'use strict';
    var moduleName = 'Henhed_Piwik/js/tracker';
    (require !== undefined) && require([moduleName], undefined, function (e) {
        if (e.requireType === 'scripterror'
            && (e.requireModules && e.requireModules[0]) === moduleName
        ) {
            require.undef(moduleName);
            define(moduleName, function () {
                var noop = function () { /* NoOp */ };
                var error = function () {
                    throw new Error('Failed to load Piwik module');
                };
                var mock = {
                    createTracker: error,
                    getPiwik: error,
                    getTracker: error,
                    push: noop
                };
                mock[moduleName] = noop;
                return mock;
            });
        }
    });
})(require);
</script>
<noscript>
    <p>
        <img src="<?= $block->getTrackingPixelUrl(); ?>"
             style="border: 0;"
             alt="" />
    </p>
</noscript>
