name: PHPUnit Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - magento-version: '2.4.2'
            php-version: '7.4'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set PHP Version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Run PHPUnit Test
        run: |
          ./dev/ci/build.sh
        env:
          M2_VERSION: ${{ matrix.magento-version }}
